"""initial schema

Revision ID: 122b4a683d44
Revises: 
Create Date: 2025-08-10 01:01:28.130016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122b4a683d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_kec', sa.String(length=10), nullable=False),
    sa.Column('nama_kec', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_kec')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('id_sobat', sa.String(length=20), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('desa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_desa', sa.String(length=10), nullable=False),
    sa.Column('nama_desa', sa.String(length=100), nullable=False),
    sa.Column('kode_kec', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['kode_kec'], ['kecamatan.kode_kec'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_desa')
    )
    op.create_table('log_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aktivitas', sa.Text(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=True),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('foto_bukti', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progres_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('jumlah_dsrt', sa.Integer(), nullable=True),
    sa.Column('jumlah_selesai', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blok_sensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_bs', sa.String(length=15), nullable=False),
    sa.Column('nks', sa.String(length=6), nullable=False),
    sa.Column('kode_desa', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['kode_desa'], ['desa.kode_desa'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_bs'),
    sa.UniqueConstraint('nks')
    )
    op.create_table('dsrt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.Column('kode_bs', sa.String(length=15), nullable=True),
    sa.Column('nks', sa.String(length=6), nullable=True),
    sa.Column('no_urut', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kode_bs'], ['blok_sensus.kode_bs'], ),
    sa.ForeignKeyConstraint(['nks'], ['blok_sensus.nks'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_dsrt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsrt_id', sa.Integer(), nullable=True),
    sa.Column('url_foto', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dsrt_id'], ['dsrt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isian_dsrt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dsrt_id', sa.Integer(), nullable=True),
    sa.Column('tanggal_pendataan', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nama_krt', sa.String(length=100), nullable=True),
    sa.Column('jumlah_art', sa.Integer(), nullable=True),
    sa.Column('pengeluaran_makanan', sa.Integer(), nullable=True),
    sa.Column('pengeluaran_nonmakanan', sa.Integer(), nullable=True),
    sa.Column('rata_rata_perkapita', sa.Float(), nullable=True),
    sa.Column('transportasi', sa.String(length=100), nullable=True),
    sa.Column('art_sekolah', sa.Integer(), nullable=True),
    sa.Column('art_bpjs', sa.Integer(), nullable=True),
    sa.Column('ijazah_krt', sa.String(length=50), nullable=True),
    sa.Column('menerima_bantuan', sa.Boolean(), nullable=True),
    sa.Column('jenis_bantuan', sa.String(length=255), nullable=True),
    sa.Column('pendidikan_krt', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dsrt_id'], ['dsrt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsrt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('isian_dsrt')
    op.drop_table('foto_dsrt')
    op.drop_table('dsrt')
    op.drop_table('blok_sensus')
    op.drop_table('progres_harian')
    op.drop_table('log_aktivitas')
    op.drop_table('desa')
    op.drop_table('users')
    op.drop_table('kecamatan')
    # ### end Alembic commands ###
