"""hapus tabel bantuan

Revision ID: 6d730eaef5b6
Revises: 
Create Date: 2025-08-09 12:51:31.642762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d730eaef5b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dsrt_bantuan')
    op.drop_table('bantuan_master')
    with op.batch_alter_table('dsrt', schema=None) as batch_op:
        batch_op.drop_column('alamat')
        batch_op.drop_column('nbs')
        batch_op.drop_column('nim')

    with op.batch_alter_table('isian_dsrt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pengeluaran_makanan', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pengeluaran_nonmakanan', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rata_rata_perkapita', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transportasi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('art_sekolah', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('art_bpjs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pakai_listrik', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('jenis_bayar_listrik', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daya_listrik', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kwh_listrik', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pengeluaran_listrik', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status_rumah', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('luas_lantai', sa.Float(), nullable=True))
        batch_op.alter_column('jenis_bantuan',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('pengeluaran_total')

    with op.batch_alter_table('log_aktivitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waktu_mulai', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('waktu_selesai', sa.DateTime(), nullable=True))
        batch_op.drop_column('waktu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_aktivitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waktu', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('waktu_selesai')
        batch_op.drop_column('waktu_mulai')

    with op.batch_alter_table('isian_dsrt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pengeluaran_total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('jenis_bantuan',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('luas_lantai')
        batch_op.drop_column('status_rumah')
        batch_op.drop_column('pengeluaran_listrik')
        batch_op.drop_column('kwh_listrik')
        batch_op.drop_column('daya_listrik')
        batch_op.drop_column('jenis_bayar_listrik')
        batch_op.drop_column('pakai_listrik')
        batch_op.drop_column('art_bpjs')
        batch_op.drop_column('art_sekolah')
        batch_op.drop_column('transportasi')
        batch_op.drop_column('rata_rata_perkapita')
        batch_op.drop_column('pengeluaran_nonmakanan')
        batch_op.drop_column('pengeluaran_makanan')

    with op.batch_alter_table('dsrt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nim', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nbs', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('bantuan_master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bantuan_master_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_bantuan', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('keterangan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bantuan_master_pkey'),
    sa.UniqueConstraint('nama_bantuan', name='bantuan_master_nama_bantuan_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('dsrt_bantuan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dsrt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bantuan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bantuan_id'], ['bantuan_master.id'], name=op.f('dsrt_bantuan_bantuan_id_fkey')),
    sa.ForeignKeyConstraint(['dsrt_id'], ['dsrt.id'], name=op.f('dsrt_bantuan_dsrt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dsrt_bantuan_pkey'))
    )
    # ### end Alembic commands ###
