"""revisi tabel DSRT

Revision ID: 9c69ef4aed11
Revises: 3ade131fbbf6
Create Date: 2025-08-11 15:01:28.695771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c69ef4aed11'
down_revision = '3ade131fbbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dsrt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dsrt_nks_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dsrt', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('dsrt_nks_fkey'), 'blok_sensus', ['nks'], ['nks'])

    # ### end Alembic commands ###
